
[server]
host = "{{ parameters.SERVER_HOST }}"
port = {{ parameters.SERVER_PORT }}
debug = "{{ parameters.DEBUG }}"

[database]
host = "{{ parameters.DATABASE_HOST }}"
port = {{ parameters.DATABASE_PORT }}
database = "{{ parameters.DATABASE_NAME }}"

user = "{{ parameters.DATABASE_USER }}"
password = "{{ secrets.DATABASE_PASSWORD }}"


[urls]
ping = "{{ urls.URL_PING }}"

payments = "{{ urls.URL_PAYMENTS }}"
create_payment = "{{ urls.URL_CREATE_PAYMENT }}"
update_payment = "{{ urls.URL_UPDATE_PAYMENT }}"
delete_payment = "{{ urls.URL_DELETE_PAYMENT }}"
payment = "{{ urls.URL_PAYMENT }}"

total_payments_monthly = "{{ urls.URL_PAYMENTS_TOTAL_MONTHLY }}"

categories = "{{ urls.URL_CATEGORIES }}"
create_category = "{{ urls.URL_CREATE_CATEGORY }}"
update_category = "{{ urls.URL_UPDATE_CATEGORY }}"
category = "{{ urls.URL_CATEGORY }}"

payments_dashboard = "{{ urls.URL_PAYMENTS_DASHBOARD }}"
payments_dashboard_yearly = "{{ urls.URL_PAYMENTS_DASHBOARD_YEARLY }}"
payments_dashboard_monthly = "{{ urls.URL_PAYMENTS_DASHBOARD_MONTHLY }}"
home_page = "{{  urls.URL_HOME_PAGE }}"


[templates]
read_payments = "{{ templates.TEMPLATE_READ_PAYMENTS }}"
create_payment = "{{ templates.TEMPLATE_CREATE_PAYMENT }}"
read_payment = "{{ templates.TEMPLATE_READ_PAYMENT }}"
delete_payment = "{{ templates.TEMPLATE_DELETE_PAYMENT }}"

payments_dashboard = "{{ templates.TEMPLATE_PAYMENTS_DASHBOARD }}"
payments_dashboard_yearly = "{{ templates.TEMPLATE_PAYMENTS_DASHBOARD_YEARLY }}"
payments_dashboard_monthly = "{{ templates.TEMPLATE_PAYMENTS_DASHBOARD_MONTHLY }}"


read_categories = "{{ templates.TEMPLATE_READ_CATEGORIES }}"
create_category = "{{ templates.TEMPLATE_CREATE_CATEGORY }}"
read_category = "{{ templates.TEMPLATE_READ_CATEGORY }}"

home_page = "{{  templates.TEMPLATE_HOME_PAGE }}"