
[server]
host = "{{ parameters.SERVER_HOST }}"
port = {{ parameters.SERVER_PORT }}

[database]
host = "{{ parameters.DATABASE_HOST }}"
port = {{ parameters.DATABASE_PORT }}
database = "{{ parameters.DATABASE_NAME }}"
user = "{{ parameters.DATABASE_USER }}"
password = "{{ secrets.DATABASE_PASSWORD }}"

[urls]
ping = "{{ urls.URL_PING }}"
expenses = "{{ urls.URL_EXPENSES }}"
create_expense = "{{ urls.URL_CREATE_EXPENSE }}"
update_expense = "{{ urls.URL_UPDATE_EXPENSE }}"
delete_expense = "{{ urls.URL_DELETE_EXPENSE }}"
expense = "{{ urls.URL_EXPENSE }}"

[templates]
read_expenses = "{{ templates.TEMPLATE_READ_EXPENSES }}"
create_expense = "{{ templates.TEMPLATE_CREATE_EXPENSE }}"
read_expense = "{{ templates.TEMPLATE_READ_EXPENSE }}"
