
[server]
host = "{{ parameters.SERVER_HOST }}"
port = {{ parameters.SERVER_PORT }}

[database]
host = "{{ parameters.DATABASE_HOST }}"
port = {{ parameters.DATABASE_PORT }}
database = "{{ parameters.DATABASE_NAME }}"
user = "{{ parameters.DATABASE_USER }}"
password = "{{ secrets.DATABASE_PASSWORD }}"

[urls]
ping = "{{ parameters.URL_PING }}"
expenses = "{{ parameters.URL_EXPENSES }}"
expense = "{{ parameters.URL_EXPENSE }}"

[templates]
read_expenses = "{{ parameters.TEMPLATE_READ_EXPENSES }}"
read_expense = "{{ parameters.TEMPLATE_READ_EXPENSE }}"
