[parameters]

# ---------- SERVER --------------
SERVER_HOST = "0.0.0.0"
SERVER_PORT = 8080
# ---------- URLS --------------
URL_PING = "/ping"
URL_EXPENSES = "/expenses"




[secrets]
# ---------- DATABASE --------------
DATABASE_PASSWORD = "1234"