[parameters]

# ---------- SERVER --------------
SERVER_HOST = "0.0.0.0"
SERVER_PORT = 8080
# ---------- URLS --------------
URL_PING = "/ping"
URL_EXPENSES = "/expenses"

# ---------- TEMPLATES --------------
TEMPLATE_READ_EXPENSES = "pages/expenses/list.html"

[secrets]
# ---------- DATABASE --------------
DATABASE_PASSWORD = "1234"