[parameters]

# ---------- SERVER --------------
SERVER_HOST = "localhost"
SERVER_PORT = 1919

# ---------- DATABASE --------------
DATABASE_HOST = "localhost"
DATABASE_PORT = 5432
DATABASE_NAME = "beeb"
DATABASE_USER = "postgres"

# ---------- URLS --------------
URL_PING = "/ping"
URL_EXPENSES = "/expenses"

[secrets]
# ---------- DATABASE --------------
DATABASE_PASSWORD = "1234"