[parameters]

# ---------- SERVER --------------
SERVER_HOST = "localhost"
SERVER_PORT = 1919

# ---------- DATABASE --------------
DATABASE_HOST = "localhost"
DATABASE_PORT = 5432
DATABASE_NAME = "beeb"
DATABASE_USER = "postgres"

[urls]
# ---------- URLS --------------
URL_PING = "/ping"
URL_EXPENSES = "/expenses"
URL_EXPENSES_TOTAL = "/expenses-total"
URL_EXPENSES_TOTAL_MONTHLY = "/expenses-total-monthly"
URL_CREATE_EXPENSE = "/expenses/create"
URL_UPDATE_EXPENSE = "/expenses/update/{expense_id}"
URL_DELETE_EXPENSE = "/expenses/delete/{expense_id}"
URL_EXPENSE = "/expenses/{expense_id}"

[templates]
# ---------- TEMPLATES --------------
TEMPLATE_READ_EXPENSES = "pages/expenses/list.html"
TEMPLATE_READ_EXPENSE = "pages/expenses/read.html"
TEMPLATE_CREATE_EXPENSE = "pages/expenses/create.html"
TEMPLATE_DELETE_EXPENSE = "modals/delete_expense.html"
TEMPLATE_EXPENSES_TOTAL_MONTLY = "pages/expenses/total_monthly.html"
TEMPLATE_EXPENSES_TOTAL = "pages/expenses/total.html"

[secrets]
# ---------- DATABASE --------------
DATABASE_PASSWORD = "1234"