[parameters]

# ---------- SERVER --------------
SERVER_HOST = "0.0.0.0"
SERVER_PORT = 1919
DEBUG = "True"

# ---------- DATABASE --------------
DATABASE_HOST = "0.0.0.0"
DATABASE_PORT = 5432
DATABASE_NAME = "beeb-dev"
DATABASE_USER = "postgres"


[urls]
# ---------- URLS --------------
URL_PING = "/ping"

URL_CREATE_USER = "/users/create"
URL_LOGIN = "/login"
URL_SIGNUP = "/signup"

URL_PAYMENTS = "/payments"
URL_PAYMENTS_TOTAL_MONTHLY = "/payments-total-monthly"
URL_CREATE_PAYMENT = "/payments/create"
URL_UPDATE_PAYMENT = "/payments/update/{payment_id}"
URL_DELETE_PAYMENT = "/payments/delete/{payment_id}"
URL_PAYMENT = "/payments/{payment_id}"

URL_CATEGORIES = "/categories"
URL_CREATE_CATEGORY = "/categories/create"
URL_UPDATE_CATEGORY = "/categories/update/{category_id}"
URL_CATEGORY = "/categories/{category_id}"

URL_PAYMENTS_DASHBOARD = "/dashboard"
URL_PAYMENTS_DASHBOARD_YEARLY = "/dashboard/{year}"
URL_PAYMENTS_DASHBOARD_MONTHLY = "/dashboard/{year}/{month}"
URL_HOME_PAGE = "/"


[templates]
# ---------- TEMPLATES --------------
TEMPLATE_SIGNUP = "/modals/signup.html"
TEMPLATE_LOGIN = "pages/auth/login.html"


TEMPLATE_READ_PAYMENTS = "pages/payments/list.html"
TEMPLATE_READ_PAYMENT = "pages/payments/read.html"
TEMPLATE_CREATE_PAYMENT = "pages/payments/create.html"
TEMPLATE_DELETE_PAYMENT = "modals/delete_payment.html"
TEMPLATE_PAYMENTS_DASHBOARD = "pages/payments/total.html"
TEMPLATE_PAYMENTS_DASHBOARD_YEARLY = "pages/payments/total_yearly.html"
TEMPLATE_PAYMENTS_DASHBOARD_MONTHLY = "pages/payments/total_monthly.html"

TEMPLATE_READ_CATEGORIES = "pages/categories/list.html"
TEMPLATE_CREATE_CATEGORY = "pages/categories/create.html"
TEMPLATE_READ_CATEGORY = "pages/categories/read.html"

TEMPLATE_HOME_PAGE = "pages/home_page.html"

[secrets]
# ---------- DATABASE --------------
DATABASE_PASSWORD = "1234"

# ---------- SALT FOR USER PASSWORDS HASH --------------
SALT = "beeb"