[parameters]

# ---------- SERVER --------------
SERVER_HOST = "localhost"
SERVER_PORT = 1919

# ---------- DATABASE --------------
DATABASE_HOST = "localhost"
DATABASE_PORT = 5432
DATABASE_NAME = "beeb"
DATABASE_USER = "postgres"

# ---------- URLS --------------
URL_PING = "/ping"
URL_EXPENSES = "/expenses"
URL_EXPENSE = "/expenses/{expense_id}"

# ---------- TEMPLATES --------------
TEMPLATE_READ_EXPENSES = "pages/expenses/list.html"
TEMPLATE_READ_EXPENSE = "pages/expenses/read.html"

[secrets]
# ---------- DATABASE --------------
DATABASE_PASSWORD = "1234"